name: version_bump
permissions:
  contents: write
on:
  workflow_dispatch:

jobs:
  build:
    name: version bump
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          cache: true

      - name: Run version bump
        run: |
          git fetch --unshallow origin
          deno run -A jsr:@orz/bump-workspaces@^0.1/cli
        env:
          GITHUB_TOKEN: ${{ secrets.ORZBOT_PAT }}
          GIT_USER_NAME: "orzBot"
          GIT_USER_EMAIL: "orzbot@users.noreply.github.com"
